#ifndef __MY_MATH_LIB_H
#define __MY_MATH_LIB_H
// Définition d'une fonction de calcul de factorielle.
unsigned int fact( unsigned int value );
// Définition d'une fonction d'élévation à une puissance données.
int power( int value, unsigned int pow );
// Définition d'une fonction qui affiche bonjour:Exercice 1
void afficherbonjour();
// Définition d'une fonction qui donne l'inverse d'un nombre entier :Exercice 2
int inverser(int n);
// Définition d'une fonction de calcul de produit de deux reéls:Exercice 3
float produit(float a, float b);
// Définition d'une fonction qui donne la parité d'un entier:Exercice 4
void parite(int x);
// Définition d'une fonction qui compare deux entiers:Exercice 5
void comparer(int c, int d);
//definition d'une fonction qui classe trois nombres entiers:Exercice 6
void ranger(int x, int y, int z);
// Définition d'une fonction de permutation du contenu de deux caractere:Exercice 16
void permuter(char *m, char *n);
// Définition d'une fonction qui renvoie la somme de deux entiers:Exercice 17
int Somme(int a, int b);
#endif
